1. Added font packages in order to prevent crashes in some tests 2. Added virtual display initialization check

diff --git a/package_test/python3.11/opensuse_15.5/run_dora b/package_test/python3.11/opensuse_15.5/run_dora
--- a/package_test/python3.11/opensuse_15.5/run_dora
+++ b/package_test/python3.11/opensuse_15.5/run_dora
@@ -13,6 +13,12 @@ pkill Xvfb > /dev/null
 export DISPLAY=:99
 Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
 sleep 1
+if xset q > /dev/null 2>&1; then
+    echo "" && echo "X display has been initialized successfully" && echo ""
+else
+    echo "" && echo "X display initialization failed"  && echo ""
+    exit 1
+fi
 /usr/local/lib64/python3.11/site-packages/smlp/run_smlp.py \
          -data smlp/regr_smlp/data/smlp_toy_num_resp_mult.csv \
          -out_dir ./ \
